# render.yaml
services:
  - type: web
    name: alpphas-gym-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DB_HOST
        value: alpphasgym-db.cd6g2sg0apgt.us-east-2.rds.amazonaws.com
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: jvbPjdbLCb3UoyKeHnNH5joqnEjD8MBbAcF2
      - key: DB_NAME
        value: alpphas_gym
      - key: DB_PORT
        value: 3306
      - key: SECRET_KEY
        value: jvbPjdbLCb3UoyKeHnNH5joqnEjD8MBbAcF2